const MADHYAMAKA_DATA = [
  {
    id: "md_931",
    dsbc_id: 931,
    category: "madhyamaka",
    title_thai: "มูลมัธยมากการิกา",
    title_sanskrit: "Mūlamadhyamakakārikā prajñā nāma",
    title_english: "Mūlamadhyamakakārikā prajñā nāma",
    folder: "madhyamaka/0931_m_lamadhyamakak_rik_praj_n_ma",
    priority: 1,
    status: "pending",
    description: "มูลมัธยมากการิกา — คัมภีร์มัธยมกะ (DSBC 931)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Mūlamadhyamakakārikā prajñā nāma", title_sanskrit: "Mūlamadhyamakakārikā prajñā nāma", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/931"
  },
  {
    id: "md_254",
    dsbc_id: 254,
    category: "madhyamaka",
    title_thai: "วิเคราะห์วยวรตน์",
    title_sanskrit: "Vigrahavyāvartanī",
    title_english: "Vigrahavyāvartanī",
    folder: "madhyamaka/0254_vigrahavy_vartan",
    priority: 2,
    status: "pending",
    description: "วิเคราะห์วยวรตน์ — คัมภีร์มัธยมกะ (DSBC 254)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Vigrahavyāvartanī", title_sanskrit: "Vigrahavyāvartanī", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/254"
  },
  {
    id: "md_252",
    dsbc_id: 252,
    category: "madhyamaka",
    title_thai: "ศูนยตาสัปตติ",
    title_sanskrit: "Śūnyatāsaptatiḥ",
    title_english: "Śūnyatāsaptatiḥ",
    folder: "madhyamaka/0252_nyat_saptati",
    priority: 3,
    status: "pending",
    description: "ศูนยตาสัปตติ — คัมภีร์มัธยมกะ (DSBC 252)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Śūnyatāsaptatiḥ", title_sanskrit: "Śūnyatāsaptatiḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/252"
  },
  {
    id: "md_255",
    dsbc_id: 255,
    category: "madhyamaka",
    title_thai: "ยุติษัษฏิการิกา",
    title_sanskrit: "Yuktiṣaṣṭikārikā",
    title_english: "Yuktiṣaṣṭikārikā",
    folder: "madhyamaka/0255_yukti_a_ik_rik",
    priority: 4,
    status: "pending",
    description: "ยุติษัษฏิการิกา — คัมภีร์มัธยมกะ (DSBC 255)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Yuktiṣaṣṭikārikā", title_sanskrit: "Yuktiṣaṣṭikārikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/255"
  },
  {
    id: "md_248",
    dsbc_id: 248,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทหฤทยการิกา",
    title_sanskrit: "Pratītyasamutpādahṛdayakārikā",
    title_english: "Pratītyasamutpādahṛdayakārikā",
    folder: "madhyamaka/0248_prat_tyasamutp_dah_dayak_rik",
    priority: 5,
    status: "pending",
    description: "ปฏิจจสมุปบาทหฤทยการิกา — คัมภีร์มัธยมกะ (DSBC 248)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādahṛdayakārikā", title_sanskrit: "Pratītyasamutpādahṛdayakārikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/248"
  },
  {
    id: "md_237",
    dsbc_id: 237,
    category: "madhyamaka",
    title_thai: "จตุหศตกา",
    title_sanskrit: "Catuḥ śatikā",
    title_english: "Catuḥ śatikā",
    folder: "madhyamaka/0237_catu_atik",
    priority: 6,
    status: "pending",
    description: "จตุหศตกา — คัมภีร์มัธยมกะ (DSBC 237)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Catuḥ śatikā", title_sanskrit: "Catuḥ śatikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/237"
  },
  {
    id: "md_243",
    dsbc_id: 243,
    category: "madhyamaka",
    title_thai: "มัธยมกาวตาร",
    title_sanskrit: "Madhyamakāvatāraḥ",
    title_english: "Madhyamakāvatāraḥ",
    folder: "madhyamaka/0243_madhyamak_vat_ra",
    priority: 7,
    status: "pending",
    description: "มัธยมกาวตาร — คัมภีร์มัธยมกะ (DSBC 243)",
    chapters_count: 5,
    chapters: [
      { id: 1, title_thai: "Prathamaścittotpādaḥ", title_sanskrit: "Prathamaścittotpādaḥ", status: "pending" },
      { id: 2, title_thai: "Dvitīyaścittotpādaḥ", title_sanskrit: "Dvitīyaścittotpādaḥ", status: "pending" },
      { id: 3, title_thai: "Tṛtīyaścittotpādaḥ", title_sanskrit: "Tṛtīyaścittotpādaḥ", status: "pending" },
      { id: 4, title_thai: "Caturthaścittotpādaḥ", title_sanskrit: "Caturthaścittotpādaḥ", status: "pending" },
      { id: 5, title_thai: "Pañcamaścittotpādaḥ", title_sanskrit: "Pañcamaścittotpādaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/243"
  },
  {
    id: "md_852",
    dsbc_id: 852,
    category: "madhyamaka",
    title_thai: "มัธยมกาวตารการิกา",
    title_sanskrit: "Madhyamakāvatārakārikā",
    title_english: "Madhyamakāvatārakārikā",
    folder: "madhyamaka/0852_madhyamak_vat_rak_rik",
    priority: 8,
    status: "pending",
    description: "มัธยมกาวตารการิกา — คัมภีร์มัธยมกะ (DSBC 852)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Madhyamakāvatāra-kārikā", title_sanskrit: "Madhyamakāvatāra-kārikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/852"
  },
  {
    id: "md_887",
    dsbc_id: 887,
    category: "madhyamaka",
    title_thai: "มัธยมกาวตารภาษยะ",
    title_sanskrit: "Madhyamakāvatārabhāṣya",
    title_english: "Madhyamakāvatārabhāṣya",
    folder: "madhyamaka/0887_madhyamak_vat_rabh_ya",
    priority: 9,
    status: "pending",
    description: "มัธยมกาวตารภาษยะ — คัมภีร์มัธยมกะ (DSBC 887)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Madhyamakāvatārabhāṣya", title_sanskrit: "Madhyamakāvatārabhāṣya", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/887"
  },
  {
    id: "md_247",
    dsbc_id: 247,
    category: "madhyamaka",
    title_thai: "ปราสันนปทา",
    title_sanskrit: "Prasannapadā (madhyamakavṛtti)",
    title_english: "Prasannapadā (madhyamakavṛtti)",
    folder: "madhyamaka/0247_prasannapad_madhyamakav_tti",
    priority: 10,
    status: "pending",
    description: "ปราสันนปทา — คัมภีร์มัธยมกะ (DSBC 247)",
    chapters_count: 27,
    chapters: [
      { id: 1, title_thai: "Prathamaṁ prakaraṇam", title_sanskrit: "Prathamaṁ prakaraṇam", status: "pending" },
      { id: 2, title_thai: "Dvitīyaṁ prakaraṇam", title_sanskrit: "Dvitīyaṁ prakaraṇam", status: "pending" },
      { id: 3, title_thai: "Tṛtīyaṁ prakaraṇam", title_sanskrit: "Tṛtīyaṁ prakaraṇam", status: "pending" },
      { id: 4, title_thai: "Caturtha prakaraṇam", title_sanskrit: "Caturtha prakaraṇam", status: "pending" },
      { id: 5, title_thai: "Pañcamaṁ prakaraṇam", title_sanskrit: "Pañcamaṁ prakaraṇam", status: "pending" },
      { id: 6, title_thai: "Ṣaṣṭhaṁ prakaraṇam", title_sanskrit: "Ṣaṣṭhaṁ prakaraṇam", status: "pending" },
      { id: 7, title_thai: "Saptamaṁ prakaraṇam", title_sanskrit: "Saptamaṁ prakaraṇam", status: "pending" },
      { id: 8, title_thai: "Aṣṭamaṁ prakaraṇam", title_sanskrit: "Aṣṭamaṁ prakaraṇam", status: "pending" },
      { id: 9, title_thai: "Navamaṁ prakaraṇam", title_sanskrit: "Navamaṁ prakaraṇam", status: "pending" },
      { id: 10, title_thai: "Daśamaṁ prakaraṇam", title_sanskrit: "Daśamaṁ prakaraṇam", status: "pending" },
      { id: 11, title_thai: "Ekādaśamaṁ prakaraṇam", title_sanskrit: "Ekādaśamaṁ prakaraṇam", status: "pending" },
      { id: 12, title_thai: "Dvādaśamaṁ prakaraṇam", title_sanskrit: "Dvādaśamaṁ prakaraṇam", status: "pending" },
      { id: 13, title_thai: "Trayodaśamaṁ prakaraṇam", title_sanskrit: "Trayodaśamaṁ prakaraṇam", status: "pending" },
      { id: 14, title_thai: "Caturdaśamaṁ prakaraṇam", title_sanskrit: "Caturdaśamaṁ prakaraṇam", status: "pending" },
      { id: 15, title_thai: "Pañcadaśamaṁ prakaraṇam", title_sanskrit: "Pañcadaśamaṁ prakaraṇam", status: "pending" },
      { id: 16, title_thai: "Ṣoḍaśamaṁ prakaraṇam", title_sanskrit: "Ṣoḍaśamaṁ prakaraṇam", status: "pending" },
      { id: 17, title_thai: "Saptadaśamaṁ prakaraṇam", title_sanskrit: "Saptadaśamaṁ prakaraṇam", status: "pending" },
      { id: 18, title_thai: "Aṣṭādaśamaṁ prakaraṇam", title_sanskrit: "Aṣṭādaśamaṁ prakaraṇam", status: "pending" },
      { id: 19, title_thai: "Ekonaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Ekonaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 20, title_thai: "Viṁśatitamaṁ prakaraṇam", title_sanskrit: "Viṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 21, title_thai: "Ekaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Ekaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 22, title_thai: "dvāviṁśatitamaṁ prakaraṇam", title_sanskrit: "dvāviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 23, title_thai: "Trayoviṁśatitamaṁ prakaraṇam", title_sanskrit: "Trayoviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 24, title_thai: "Caturviṁśatitamaṁ prakaraṇam", title_sanskrit: "Caturviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 25, title_thai: "Pañcaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Pañcaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 26, title_thai: "Ṣaḍviṁśatitamaṁ prakaraṇam", title_sanskrit: "Ṣaḍviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 27, title_thai: "Saptaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Saptaviṁśatitamaṁ prakaraṇam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/247"
  },
  {
    id: "md_246",
    dsbc_id: 246,
    category: "madhyamaka",
    title_thai: "ปราชญาประทีป",
    title_sanskrit: "Prajñāpradīpaḥ",
    title_english: "Prajñāpradīpaḥ",
    folder: "madhyamaka/0246_praj_prad_pa",
    priority: 11,
    status: "pending",
    description: "ปราชญาประทีป — คัมภีร์มัธยมกะ (DSBC 246)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Prajñāpradīpaḥ", title_sanskrit: "Prajñāpradīpaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/246"
  },
  {
    id: "md_241",
    dsbc_id: 241,
    category: "madhyamaka",
    title_thai: "มัธยมกาโลกะ",
    title_sanskrit: "Madhyamakālokaḥ",
    title_english: "Madhyamakālokaḥ",
    folder: "madhyamaka/0241_madhyamak_loka",
    priority: 12,
    status: "pending",
    description: "มัธยมกาโลกะ — คัมภีร์มัธยมกะ (DSBC 241)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Madhyamakālokaḥ", title_sanskrit: "Madhyamakālokaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/241"
  },
  {
    id: "md_242",
    dsbc_id: 242,
    category: "madhyamaka",
    title_thai: "มัธยมกศาสตร์",
    title_sanskrit: "Madhyamakaśāstram",
    title_english: "Madhyamakaśāstram",
    folder: "madhyamaka/0242_madhyamaka_stram",
    priority: 13,
    status: "pending",
    description: "มัธยมกศาสตร์ — คัมภีร์มัธยมกะ (DSBC 242)",
    chapters_count: 27,
    chapters: [
      { id: 1, title_thai: "Pratyayaparīkṣā nāma prathamaṁ prakaraṇam", title_sanskrit: "Pratyayaparīkṣā nāma prathamaṁ prakaraṇam", status: "pending" },
      { id: 2, title_thai: "Gatāgataparīkṣā dvitīyaṁ prakaraṇam", title_sanskrit: "Gatāgataparīkṣā dvitīyaṁ prakaraṇam", status: "pending" },
      { id: 3, title_thai: "Cakṣurādīndriyaparīkṣā tṛtīyaṁ prakaraṇam", title_sanskrit: "Cakṣurādīndriyaparīkṣā tṛtīyaṁ prakaraṇam", status: "pending" },
      { id: 4, title_thai: "Skandhaparīkṣā caturthaṁ prakaraṇam", title_sanskrit: "Skandhaparīkṣā caturthaṁ prakaraṇam", status: "pending" },
      { id: 5, title_thai: "Dhātuparīkṣā pañcamaṁ prakaraṇam", title_sanskrit: "Dhātuparīkṣā pañcamaṁ prakaraṇam", status: "pending" },
      { id: 6, title_thai: "Rāgaraktaparīkṣā ṣaṣṭhaṁ prakaraṇam", title_sanskrit: "Rāgaraktaparīkṣā ṣaṣṭhaṁ prakaraṇam", status: "pending" },
      { id: 7, title_thai: "Saṁskṛtaparīkṣā saptamaṁ prakaraṇam", title_sanskrit: "Saṁskṛtaparīkṣā saptamaṁ prakaraṇam", status: "pending" },
      { id: 8, title_thai: "Karmakārakaparīkṣā aṣṭamaṁ prakaraṇam", title_sanskrit: "Karmakārakaparīkṣā aṣṭamaṁ prakaraṇam", status: "pending" },
      { id: 9, title_thai: "Pūrvaparīkṣā navamaṁ prakaraṇam", title_sanskrit: "Pūrvaparīkṣā navamaṁ prakaraṇam", status: "pending" },
      { id: 10, title_thai: "Agnīndhanaparīkṣā daśamaṁ prakaraṇam", title_sanskrit: "Agnīndhanaparīkṣā daśamaṁ prakaraṇam", status: "pending" },
      { id: 11, title_thai: "Pūrvāparakoṭiparīkṣā ekādaśamaṁ prakaraṇam", title_sanskrit: "Pūrvāparakoṭiparīkṣā ekādaśamaṁ prakaraṇam", status: "pending" },
      { id: 12, title_thai: "Duḥkhaparīkṣā dvādaśamaṁ prakaraṇam", title_sanskrit: "Duḥkhaparīkṣā dvādaśamaṁ prakaraṇam", status: "pending" },
      { id: 13, title_thai: "Saṁskāraparīkṣā trayodaśamaṁ prakaraṇam", title_sanskrit: "Saṁskāraparīkṣā trayodaśamaṁ prakaraṇam", status: "pending" },
      { id: 14, title_thai: "Saṁsargaparīkṣā caturdaśamaṁ prakaraṇam", title_sanskrit: "Saṁsargaparīkṣā caturdaśamaṁ prakaraṇam", status: "pending" },
      { id: 15, title_thai: "Svabhāvaparīkṣā pañcadaśamaṁ prakaraṇam", title_sanskrit: "Svabhāvaparīkṣā pañcadaśamaṁ prakaraṇam", status: "pending" },
      { id: 16, title_thai: "Bandhamokṣaparīkṣā ṣoḍaśamaṁ prakaraṇam", title_sanskrit: "Bandhamokṣaparīkṣā ṣoḍaśamaṁ prakaraṇam", status: "pending" },
      { id: 17, title_thai: "Karmaphalaparīkṣā saptadaśamaṁ prakaraṇam", title_sanskrit: "Karmaphalaparīkṣā saptadaśamaṁ prakaraṇam", status: "pending" },
      { id: 18, title_thai: "Ātmaparīkṣā aṣṭādaśamaṁ prakaraṇam", title_sanskrit: "Ātmaparīkṣā aṣṭādaśamaṁ prakaraṇam", status: "pending" },
      { id: 19, title_thai: "Kālaparīkṣā ekonaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Kālaparīkṣā ekonaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 20, title_thai: "Sāmagrīparīkṣā viṁśatitamaṁ prakaraṇam", title_sanskrit: "Sāmagrīparīkṣā viṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 21, title_thai: "Saṁbhavavibhavaparīkṣā ekaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Saṁbhavavibhavaparīkṣā ekaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 22, title_thai: "Tathāgataparīkṣā dvāviṁśatitamaṁ prakaraṇam", title_sanskrit: "Tathāgataparīkṣā dvāviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 23, title_thai: "Viparyāsaparīkṣā trayoviṁśatitamaṁ prakaraṇam", title_sanskrit: "Viparyāsaparīkṣā trayoviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 24, title_thai: "Āryasatyaparīkṣā caturviṁśatitamaṁ prakaraṇam", title_sanskrit: "Āryasatyaparīkṣā caturviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 25, title_thai: "Nirvāṇaparīkṣā pañcaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Nirvāṇaparīkṣā pañcaviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 26, title_thai: "Dvādaśāṅgaparīkṣā ṣaḍviṁśatitamaṁ prakaraṇam", title_sanskrit: "Dvādaśāṅgaparīkṣā ṣaḍviṁśatitamaṁ prakaraṇam", status: "pending" },
      { id: 27, title_thai: "Dṛṣṭiparīkṣā saptaviṁśatitamaṁ prakaraṇam", title_sanskrit: "Dṛṣṭiparīkṣā saptaviṁśatitamaṁ prakaraṇam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/242"
  },
  {
    id: "md_244",
    dsbc_id: 244,
    category: "madhyamaka",
    title_thai: "มัธยมารถสังคระหะ",
    title_sanskrit: "Madhyamārthasaṃgrahaḥ",
    title_english: "Madhyamārthasaṃgrahaḥ",
    folder: "madhyamaka/0244_madhyam_rthasa_graha",
    priority: 14,
    status: "pending",
    description: "มัธยมารถสังคระหะ — คัมภีร์มัธยมกะ (DSBC 244)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Madhyamārthasaṁgrahaḥ", title_sanskrit: "Madhyamārthasaṁgrahaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/244"
  },
  {
    id: "md_245",
    dsbc_id: 245,
    category: "madhyamaka",
    title_thai: "มหายานวิงศิกา",
    title_sanskrit: "Mahāyānaviṃśikā",
    title_english: "Mahāyānaviṃśikā",
    folder: "madhyamaka/0245_mah_y_navi_ik",
    priority: 15,
    status: "pending",
    description: "มหายานวิงศิกา — คัมภีร์มัธยมกะ (DSBC 245)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Mahāyānaviṁśikā", title_sanskrit: "Mahāyānaviṁśikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/245"
  },
  {
    id: "md_240",
    dsbc_id: 240,
    category: "madhyamaka",
    title_thai: "มัธยมกาหฤทยะ",
    title_sanskrit: "Madhyamakahṛdayaḥ",
    title_english: "Madhyamakahṛdayaḥ",
    folder: "madhyamaka/0240_madhyamakah_daya",
    priority: 16,
    status: "pending",
    description: "มัธยมกาหฤทยะ — คัมภีร์มัธยมกะ (DSBC 240)",
    chapters_count: 11,
    chapters: [
      { id: 1, title_thai: "prathamaḥ paricchedaḥ", title_sanskrit: "prathamaḥ paricchedaḥ", status: "pending" },
      { id: 2, title_thai: "dvitīyaḥ paricchedaḥ", title_sanskrit: "dvitīyaḥ paricchedaḥ", status: "pending" },
      { id: 3, title_thai: "tṛtīyaḥ paricchedaḥ", title_sanskrit: "tṛtīyaḥ paricchedaḥ", status: "pending" },
      { id: 4, title_thai: "caturthaḥ paricchedaḥ", title_sanskrit: "caturthaḥ paricchedaḥ", status: "pending" },
      { id: 5, title_thai: "pañcamaḥ paricchedaḥ", title_sanskrit: "pañcamaḥ paricchedaḥ", status: "pending" },
      { id: 6, title_thai: "ṣaṣṭhaḥ paricchedaḥ", title_sanskrit: "ṣaṣṭhaḥ paricchedaḥ", status: "pending" },
      { id: 7, title_thai: "saptamaḥ paricchedaḥ", title_sanskrit: "saptamaḥ paricchedaḥ", status: "pending" },
      { id: 8, title_thai: "aṣṭamaḥ paricchedaḥ", title_sanskrit: "aṣṭamaḥ paricchedaḥ", status: "pending" },
      { id: 9, title_thai: "navamaḥ paricchedaḥ", title_sanskrit: "navamaḥ paricchedaḥ", status: "pending" },
      { id: 10, title_thai: "daśamaḥ paricchedaḥ", title_sanskrit: "daśamaḥ paricchedaḥ", status: "pending" },
      { id: 11, title_thai: "ekādaśaḥ paricchedaḥ", title_sanskrit: "ekādaśaḥ paricchedaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/240"
  },
  {
    id: "md_238",
    dsbc_id: 238,
    category: "madhyamaka",
    title_thai: "หัสตวาลประกรณะ",
    title_sanskrit: "Hastavālaprakaraṇa",
    title_english: "Hastavālaprakaraṇa",
    folder: "madhyamaka/0238_hastav_laprakara_a",
    priority: 17,
    status: "pending",
    description: "หัสตวาลประกรณะ — คัมภีร์มัธยมกะ (DSBC 238)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Hastavālaprakaraṇa", title_sanskrit: "Hastavālaprakaraṇa", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/238"
  },
  {
    id: "md_239",
    dsbc_id: 239,
    category: "madhyamaka",
    title_thai: "หัสตวาลประกรณะวฤตติ",
    title_sanskrit: "Hastavālaprakaraṇavṛttiḥ",
    title_english: "Hastavālaprakaraṇavṛttiḥ",
    folder: "madhyamaka/0239_hastav_laprakara_av_tti",
    priority: 18,
    status: "pending",
    description: "หัสตวาลประกรณะวฤตติ — คัมภีร์มัธยมกะ (DSBC 239)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "hastavālaprakaraṇavṛttiḥ", title_sanskrit: "hastavālaprakaraṇavṛttiḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/239"
  },
  {
    id: "md_250",
    dsbc_id: 250,
    category: "madhyamaka",
    title_thai: "ศรณคมนเทศนา",
    title_sanskrit: "Śaraṇagamanadeśanā",
    title_english: "Śaraṇagamanadeśanā",
    folder: "madhyamaka/0250_ara_agamanade_an",
    priority: 19,
    status: "pending",
    description: "ศรณคมนเทศนา — คัมภีร์มัธยมกะ (DSBC 250)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Śaraṇagamanadeśanā", title_sanskrit: "Śaraṇagamanadeśanā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/250"
  },
  {
    id: "md_251",
    dsbc_id: 251,
    category: "madhyamaka",
    title_thai: "สัตยทวยาวตาร",
    title_sanskrit: "Satyadvayāvatāranāma",
    title_english: "Satyadvayāvatāranāma",
    folder: "madhyamaka/0251_satyadvay_vat_ran_ma",
    priority: 20,
    status: "pending",
    description: "สัตยทวยาวตาร — คัมภีร์มัธยมกะ (DSBC 251)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Satyadvayāvatāranāma", title_sanskrit: "Satyadvayāvatāranāma", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/251"
  },
  {
    id: "md_253",
    dsbc_id: 253,
    category: "madhyamaka",
    title_thai: "สูตรารถสมุจจโยปเทศ",
    title_sanskrit: "Sūtrārthasamuccayopadeśaḥ",
    title_english: "Sūtrārthasamuccayopadeśaḥ",
    folder: "madhyamaka/0253_s_tr_rthasamuccayopade_a",
    priority: 21,
    status: "pending",
    description: "สูตรารถสมุจจโยปเทศ — คัมภีร์มัธยมกะ (DSBC 253)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Sūtrārthasamuccayopadeśaḥ", title_sanskrit: "Sūtrārthasamuccayopadeśaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/253"
  },
  {
    id: "md_236",
    dsbc_id: 236,
    category: "madhyamaka",
    title_thai: "อกุโตภยะ",
    title_sanskrit: "Akutobhaya",
    title_english: "Akutobhaya",
    folder: "madhyamaka/0236_akutobhaya",
    priority: 22,
    status: "pending",
    description: "อกุโตภยะ — คัมภีร์มัธยมกะ (DSBC 236)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Akutobhaya", title_sanskrit: "Akutobhaya", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/236"
  },
  {
    id: "md_249",
    dsbc_id: 249,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทหฤทยวยาขยาน",
    title_sanskrit: "Pratītyasamutpādahṛdayavyākhyānam",
    title_english: "Pratītyasamutpādahṛdayavyākhyānam",
    folder: "madhyamaka/0249_prat_tyasamutp_dah_dayavy_khy_nam",
    priority: 23,
    status: "pending",
    description: "ปฏิจจสมุปบาทหฤทยวยาขยาน — คัมภีร์มัธยมกะ (DSBC 249)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādahṛdayavyākhyānam", title_sanskrit: "Pratītyasamutpādahṛdayavyākhyānam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/249"
  },
  {
    id: "md_721",
    dsbc_id: 721,
    category: "madhyamaka",
    title_thai: "สวภาววาทะ",
    title_sanskrit: "Svabhāvavādaḥ",
    title_english: "Svabhāvavādaḥ",
    folder: "madhyamaka/0721_svabh_vav_da",
    priority: 24,
    status: "pending",
    description: "สวภาววาทะ — คัมภีร์มัธยมกะ (DSBC 721)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Svabhāvavādaḥ", title_sanskrit: "Svabhāvavādaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/721"
  },
  {
    id: "md_896",
    dsbc_id: 896,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย",
    title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    title_english: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    folder: "madhyamaka/0896_prat_tyasamutp_dastutisubh_itah_dayam",
    priority: 25,
    status: "pending",
    description: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย — คัมภีร์มัธยมกะ (DSBC 896)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādastutisubhāṣitahṛdayam  Ācārya", title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam  Ācārya", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/896"
  },
  {
    id: "md_962",
    dsbc_id: 962,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย",
    title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    title_english: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    folder: "madhyamaka/0962_prat_tyasamutp_dastutisubh_itah_dayam",
    priority: 26,
    status: "pending",
    description: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย — คัมภีร์มัธยมกะ (DSBC 962)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādastutisubhāṣitahṛdayam", title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/962"
  },
  {
    id: "md_963",
    dsbc_id: 963,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย",
    title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    title_english: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    folder: "madhyamaka/0963_prat_tyasamutp_dastutisubh_itah_dayam",
    priority: 27,
    status: "pending",
    description: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย — คัมภีร์มัธยมกะ (DSBC 963)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādastutisubhāṣitahṛdayam", title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/963"
  },
  {
    id: "md_970",
    dsbc_id: 970,
    category: "madhyamaka",
    title_thai: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย",
    title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    title_english: "Pratītyasamutpādastutisubhāṣitahṛdayam",
    folder: "madhyamaka/0970_prat_tyasamutp_dastutisubh_itah_dayam",
    priority: 28,
    status: "pending",
    description: "ปฏิจจสมุปบาทสตติสุภาษิตหฤทย — คัมภีร์มัธยมกะ (DSBC 970)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Pratītyasamutpādastutisubhāṣitahṛdayam", title_sanskrit: "Pratītyasamutpādastutisubhāṣitahṛdayam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/970"
  },
  {
    id: "md_258",
    dsbc_id: 258,
    category: "madhyamaka",
    title_thai: "โพธิจริยาวตาร",
    title_sanskrit: "Bodhicaryāvatāraḥ",
    title_english: "Bodhicaryāvatāraḥ",
    folder: "madhyamaka/0258_bodhicary_vat_ra",
    priority: 30,
    status: "pending",
    description: "โพธิจริยาวตาร — คัมภีร์มัธยมกะ (DSBC 258)",
    chapters_count: 10,
    chapters: [
      { id: 1, title_thai: "1 bodhicittānuśaṁso nāma prathamaḥ paricchedaḥ", title_sanskrit: "1 bodhicittānuśaṁso nāma prathamaḥ paricchedaḥ", status: "pending" },
      { id: 2, title_thai: "2 pāpadeśanā nāma dvitīyaḥ paricchedaḥ", title_sanskrit: "2 pāpadeśanā nāma dvitīyaḥ paricchedaḥ", status: "pending" },
      { id: 3, title_thai: "3 bodhicittaparigraho nāma tṛtīyaḥ paricchedaḥ", title_sanskrit: "3 bodhicittaparigraho nāma tṛtīyaḥ paricchedaḥ", status: "pending" },
      { id: 4, title_thai: "4 bodhicittāpramādo nāma caturthaḥ paricchedaḥ", title_sanskrit: "4 bodhicittāpramādo nāma caturthaḥ paricchedaḥ", status: "pending" },
      { id: 5, title_thai: "5 saṁprajanyarakṣaṇaṁ nāma pañcamaḥ paricchedaḥ", title_sanskrit: "5 saṁprajanyarakṣaṇaṁ nāma pañcamaḥ paricchedaḥ", status: "pending" },
      { id: 6, title_thai: "6 kṣāntipāramitā nāma ṣaṣṭhaḥ paricchedaḥ", title_sanskrit: "6 kṣāntipāramitā nāma ṣaṣṭhaḥ paricchedaḥ", status: "pending" },
      { id: 7, title_thai: "7 vīryapāramitā nāma saptamaḥ paricchedaḥ", title_sanskrit: "7 vīryapāramitā nāma saptamaḥ paricchedaḥ", status: "pending" },
      { id: 8, title_thai: "8 dhyānapāramitā nāma aṣṭamaḥ paricchedaḥ", title_sanskrit: "8 dhyānapāramitā nāma aṣṭamaḥ paricchedaḥ", status: "pending" },
      { id: 9, title_thai: "9 prajñāpāramitā nāma navamaḥ paricchedaḥ", title_sanskrit: "9 prajñāpāramitā nāma navamaḥ paricchedaḥ", status: "pending" },
      { id: 10, title_thai: "10 pariṇāmanāparicchedo daśamaḥ", title_sanskrit: "10 pariṇāmanāparicchedo daśamaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/258"
  },
  {
    id: "md_257",
    dsbc_id: 257,
    category: "madhyamaka",
    title_thai: "ภาวนากรม",
    title_sanskrit: "Bhāvanākramaḥ",
    title_english: "Bhāvanākramaḥ",
    folder: "madhyamaka/0257_bh_van_krama",
    priority: 31,
    status: "pending",
    description: "ภาวนากรม — คัมภีร์มัธยมกะ (DSBC 257)",
    chapters_count: 3,
    chapters: [
      { id: 1, title_thai: "Bhāvanākramaḥ prathamaḥ", title_sanskrit: "Bhāvanākramaḥ prathamaḥ", status: "pending" },
      { id: 2, title_thai: "Bhāvanākramo dvitīyaḥ", title_sanskrit: "Bhāvanākramo dvitīyaḥ", status: "pending" },
      { id: 3, title_thai: "Bhāvanākramastṛtīyaḥ", title_sanskrit: "Bhāvanākramastṛtīyaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/257"
  },
  {
    id: "md_269",
    dsbc_id: 269,
    category: "madhyamaka",
    title_thai: "ศิกษาสมุจจยะ",
    title_sanskrit: "Śikṣāsamuccayaḥ",
    title_english: "Śikṣāsamuccayaḥ",
    folder: "madhyamaka/0269_ik_samuccaya",
    priority: 32,
    status: "pending",
    description: "ศิกษาสมุจจยะ — คัมภีร์มัธยมกะ (DSBC 269)",
    chapters_count: 19,
    chapters: [
      { id: 1, title_thai: "Dānapāramitā prathamaḥ paricchedaḥ", title_sanskrit: "Dānapāramitā prathamaḥ paricchedaḥ", status: "pending" },
      { id: 2, title_thai: "Saddharmaparigraho dvitīyaḥ paricchedaḥ", title_sanskrit: "Saddharmaparigraho dvitīyaḥ paricchedaḥ", status: "pending" },
      { id: 3, title_thai: "Dharmabhāṇakādirakṣā tṛtīyaḥ paricchedaḥ", title_sanskrit: "Dharmabhāṇakādirakṣā tṛtīyaḥ paricchedaḥ", status: "pending" },
      { id: 4, title_thai: "Anarthavarjanaṁ caturthaḥ paricchedaḥ", title_sanskrit: "Anarthavarjanaṁ caturthaḥ paricchedaḥ", status: "pending" },
      { id: 5, title_thai: "Śīlapāramitāyāmanarthavarjanaṁ pañcamaḥ paricchedaḥ", title_sanskrit: "Śīlapāramitāyāmanarthavarjanaṁ pañcamaḥ paricchedaḥ", status: "pending" },
      { id: 6, title_thai: "Ātmabhāvarakṣā ṣaṣṭhaḥ paricchedaḥ", title_sanskrit: "Ātmabhāvarakṣā ṣaṣṭhaḥ paricchedaḥ", status: "pending" },
      { id: 7, title_thai: "Bhogapuṇyarakṣā saptamaḥ paricchedaḥ", title_sanskrit: "Bhogapuṇyarakṣā saptamaḥ paricchedaḥ", status: "pending" },
      { id: 8, title_thai: "Pāpaśodhanaṁ nāma aṣṭamaḥ paricchedaḥ", title_sanskrit: "Pāpaśodhanaṁ nāma aṣṭamaḥ paricchedaḥ", status: "pending" },
      { id: 9, title_thai: "Kṣāntipāramitā navamaḥ paricchedaḥ", title_sanskrit: "Kṣāntipāramitā navamaḥ paricchedaḥ", status: "pending" },
      { id: 10, title_thai: "Vīryapāramitā daśamaḥ paricchedaḥ", title_sanskrit: "Vīryapāramitā daśamaḥ paricchedaḥ", status: "pending" },
      { id: 11, title_thai: "Araṇyasaṁvarṇanaṁ nāmaikādaśaḥ paricchedaḥ", title_sanskrit: "Araṇyasaṁvarṇanaṁ nāmaikādaśaḥ paricchedaḥ", status: "pending" },
      { id: 12, title_thai: "Cittaparikarma dvādaśaḥ paricchedaḥ", title_sanskrit: "Cittaparikarma dvādaśaḥ paricchedaḥ", status: "pending" },
      { id: 13, title_thai: "Smṛtyupasthānaparicchedaḥ trayodaśaḥ", title_sanskrit: "Smṛtyupasthānaparicchedaḥ trayodaśaḥ", status: "pending" },
      { id: 14, title_thai: "Ātmabhāvapariśuddhiparicchedaścaturdaśaḥ", title_sanskrit: "Ātmabhāvapariśuddhiparicchedaścaturdaśaḥ", status: "pending" },
      { id: 15, title_thai: "Bhogapuṇyaśuddhiḥ pañcadaśaḥ paricchedaḥ", title_sanskrit: "Bhogapuṇyaśuddhiḥ pañcadaśaḥ paricchedaḥ", status: "pending" },
      { id: 16, title_thai: "Bhadracaryāvidhiḥ ṣoḍaśaḥ paricchedaḥ", title_sanskrit: "Bhadracaryāvidhiḥ ṣoḍaśaḥ paricchedaḥ", status: "pending" },
      { id: 17, title_thai: "Vandanānuśaṁsā saptadaśaḥ paricchedaḥ", title_sanskrit: "Vandanānuśaṁsā saptadaśaḥ paricchedaḥ", status: "pending" },
      { id: 18, title_thai: "Ratnatrayānusmṛtirnāmāṣṭādaśaḥ paricchedaḥ", title_sanskrit: "Ratnatrayānusmṛtirnāmāṣṭādaśaḥ paricchedaḥ", status: "pending" },
      { id: 19, title_thai: "Puṇyavṛddhirnāma navadaśaḥ paricchedaḥ", title_sanskrit: "Puṇyavṛddhirnāma navadaśaḥ paricchedaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/269"
  },
  {
    id: "md_268",
    dsbc_id: 268,
    category: "madhyamaka",
    title_thai: "ศิกษาสมุจจยการิกา",
    title_sanskrit: "Śikṣāsamuccaya kārikā",
    title_english: "Śikṣāsamuccaya kārikā",
    folder: "madhyamaka/0268_ik_samuccaya_k_rik",
    priority: 33,
    status: "pending",
    description: "ศิกษาสมุจจยการิกา — คัมภีร์มัธยมกะ (DSBC 268)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Śikṣāsamuccaya kārikā", title_sanskrit: "Śikṣāsamuccaya kārikā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/268"
  },
  {
    id: "md_259",
    dsbc_id: 259,
    category: "madhyamaka",
    title_thai: "โพธิจริยาวตาร ปัญชิกา",
    title_sanskrit: "Bodhicaryāvatāraḥ (pañjikā)",
    title_english: "Bodhicaryāvatāraḥ (pañjikā)",
    folder: "madhyamaka/0259_bodhicary_vat_ra_pa_jik",
    priority: 34,
    status: "pending",
    description: "โพธิจริยาวตาร ปัญชิกา — คัมภีร์มัธยมกะ (DSBC 259)",
    chapters_count: 10,
    chapters: [
      { id: 1, title_thai: "1 bodhicittānuśaṁso nāma prathamaḥ paricchedaḥ", title_sanskrit: "1 bodhicittānuśaṁso nāma prathamaḥ paricchedaḥ", status: "pending" },
      { id: 2, title_thai: "2 pāpadeśanā nāma dvitīyaḥ paricchedaḥ", title_sanskrit: "2 pāpadeśanā nāma dvitīyaḥ paricchedaḥ", status: "pending" },
      { id: 3, title_thai: "3 bodhicittaparigraho nāma tṛtīyaḥ paricchedaḥ", title_sanskrit: "3 bodhicittaparigraho nāma tṛtīyaḥ paricchedaḥ", status: "pending" },
      { id: 4, title_thai: "4 bodhicittāpramādo nāma caturthaḥ paricchedaḥ", title_sanskrit: "4 bodhicittāpramādo nāma caturthaḥ paricchedaḥ", status: "pending" },
      { id: 5, title_thai: "5 saṁprajanyarakṣaṇaṁ nāma pañcamaḥ paricchedaḥ", title_sanskrit: "5 saṁprajanyarakṣaṇaṁ nāma pañcamaḥ paricchedaḥ", status: "pending" },
      { id: 6, title_thai: "6 kṣāntipāramitā nāma ṣaṣṭhaḥ paricchedaḥ", title_sanskrit: "6 kṣāntipāramitā nāma ṣaṣṭhaḥ paricchedaḥ", status: "pending" },
      { id: 7, title_thai: "7 vīryapāramitā nāma saptamaḥ paricchedaḥ", title_sanskrit: "7 vīryapāramitā nāma saptamaḥ paricchedaḥ", status: "pending" },
      { id: 8, title_thai: "8 dhyānapāramitā nāma aṣṭamaḥ paricchedaḥ", title_sanskrit: "8 dhyānapāramitā nāma aṣṭamaḥ paricchedaḥ", status: "pending" },
      { id: 9, title_thai: "9 prajñāpāramitā nāma navamaḥ paricchedaḥ", title_sanskrit: "9 prajñāpāramitā nāma navamaḥ paricchedaḥ", status: "pending" },
      { id: 10, title_thai: "10 pariṇāmanāparicchedo daśamaḥ", title_sanskrit: "10 pariṇāmanāparicchedo daśamaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/259"
  },
  {
    id: "md_260",
    dsbc_id: 260,
    category: "madhyamaka",
    title_thai: "โพธิปถประทีป",
    title_sanskrit: "Bodhipathapradīpaḥ",
    title_english: "Bodhipathapradīpaḥ",
    folder: "madhyamaka/0260_bodhipathaprad_pa",
    priority: 35,
    status: "pending",
    description: "โพธิปถประทีป — คัมภีร์มัธยมกะ (DSBC 260)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Bodhipathapradīpaḥ", title_sanskrit: "Bodhipathapradīpaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/260"
  },
  {
    id: "md_261",
    dsbc_id: 261,
    category: "madhyamaka",
    title_thai: "โพธิสัตตวงศ์กัมมิกมรรคาวตารเทศนา",
    title_sanskrit: "Bodhisattvādikarmika-mārgāvatāra-deśanā",
    title_english: "Bodhisattvādikarmika-mārgāvatāra-deśanā",
    folder: "madhyamaka/0261_bodhisattv_dikarmika_m_rg_vat_ra_de_an",
    priority: 36,
    status: "pending",
    description: "โพธิสัตตวงศ์กัมมิกมรรคาวตารเทศนา — คัมภีร์มัธยมกะ (DSBC 261)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Bodhisattvādikarmika-mārgāvatāra-deśanā", title_sanskrit: "Bodhisattvādikarmika-mārgāvatāra-deśanā", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/261"
  },
  {
    id: "md_262",
    dsbc_id: 262,
    category: "madhyamaka",
    title_thai: "โพธยาปัตติเทศนาวฤตติ",
    title_sanskrit: "Bodhyāpattideśanāvṛttiḥ",
    title_english: "Bodhyāpattideśanāvṛttiḥ",
    folder: "madhyamaka/0262_bodhy_pattide_an_v_tti",
    priority: 37,
    status: "pending",
    description: "โพธยาปัตติเทศนาวฤตติ — คัมภีร์มัธยมกะ (DSBC 262)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Bodhyāpattideśanāvṛttiḥ", title_sanskrit: "Bodhyāpattideśanāvṛttiḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/262"
  },
  {
    id: "md_263",
    dsbc_id: 263,
    category: "madhyamaka",
    title_thai: "จริยาสังคหะประทีป",
    title_sanskrit: "Caryāsaṅgrahapradīpaḥ",
    title_english: "Caryāsaṅgrahapradīpaḥ",
    folder: "madhyamaka/0263_cary_sa_grahaprad_pa",
    priority: 38,
    status: "pending",
    description: "จริยาสังคหะประทีป — คัมภีร์มัธยมกะ (DSBC 263)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Caryāsaṅgrahapradīpaḥ", title_sanskrit: "Caryāsaṅgrahapradīpaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/263"
  },
  {
    id: "md_264",
    dsbc_id: 264,
    category: "madhyamaka",
    title_thai: "จิตโตตปาทสังวรวิธิกรมะ",
    title_sanskrit: "Cittotpādasaṃvaravidhikramaḥ",
    title_english: "Cittotpādasaṃvaravidhikramaḥ",
    folder: "madhyamaka/0264_cittotp_dasa_varavidhikrama",
    priority: 39,
    status: "pending",
    description: "จิตโตตปาทสังวรวิธิกรมะ — คัมภีร์มัธยมกะ (DSBC 264)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Cittotpādasaṁvaravidhikramaḥ", title_sanskrit: "Cittotpādasaṁvaravidhikramaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/264"
  },
  {
    id: "md_265",
    dsbc_id: 265,
    category: "madhyamaka",
    title_thai: "ครภสังคระหะ",
    title_sanskrit: "Garbha-saṅgrahaḥ",
    title_english: "Garbha-saṅgrahaḥ",
    folder: "madhyamaka/0265_garbha_sa_graha",
    priority: 40,
    status: "pending",
    description: "ครภสังคระหะ — คัมภีร์มัธยมกะ (DSBC 265)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Garbha-saṅgrahaḥ", title_sanskrit: "Garbha-saṅgrahaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/265"
  },
  {
    id: "md_266",
    dsbc_id: 266,
    category: "madhyamaka",
    title_thai: "มหายานปถสาธนสังคระหะ",
    title_sanskrit: "Mahāyānapathasādhanasaṅgrahaḥ",
    title_english: "Mahāyānapathasādhanasaṅgrahaḥ",
    folder: "madhyamaka/0266_mah_y_napathas_dhanasa_graha",
    priority: 41,
    status: "pending",
    description: "มหายานปถสาธนสังคระหะ — คัมภีร์มัธยมกะ (DSBC 266)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Mahāyānapathasādhanasaṅgrahaḥ", title_sanskrit: "Mahāyānapathasādhanasaṅgrahaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/266"
  },
  {
    id: "md_267",
    dsbc_id: 267,
    category: "madhyamaka",
    title_thai: "สมาธิสัมภารปริวรรต",
    title_sanskrit: "Samādhisaṃbhāraparivartaḥ",
    title_english: "Samādhisaṃbhāraparivartaḥ",
    folder: "madhyamaka/0267_sam_dhisa_bh_raparivarta",
    priority: 42,
    status: "pending",
    description: "สมาธิสัมภารปริวรรต — คัมภีร์มัธยมกะ (DSBC 267)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Samādhisaṁbhāraparivartaḥ", title_sanskrit: "Samādhisaṁbhāraparivartaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/267"
  },
  {
    id: "md_256",
    dsbc_id: 256,
    category: "madhyamaka",
    title_thai: "อาปัตติเทศนาวิธิ",
    title_sanskrit: "Āpattideśanāvidhiḥ",
    title_english: "Āpattideśanāvidhiḥ",
    folder: "madhyamaka/0256_pattide_an_vidhi",
    priority: 43,
    status: "pending",
    description: "อาปัตติเทศนาวิธิ — คัมภีร์มัธยมกะ (DSBC 256)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Āpattideśanāvidhiḥ", title_sanskrit: "Āpattideśanāvidhiḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/256"
  },
  {
    id: "md_891",
    dsbc_id: 891,
    category: "madhyamaka",
    title_thai: "รัตนกรัณฑทฆาฏมัธยม",
    title_sanskrit: "Ratnakaraṇḍodghāṭamadhyamanāmopadeśaḥ",
    title_english: "Ratnakaraṇḍodghāṭamadhyamanāmopadeśaḥ",
    folder: "madhyamaka/0891_ratnakara_odgh_amadhyaman_mopade_a",
    priority: 44,
    status: "pending",
    description: "รัตนกรัณฑทฆาฏมัธยม — คัมภีร์มัธยมกะ (DSBC 891)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "Ratnakaraṇḍodghāṭamadhyamanāmopadeśaḥ", title_sanskrit: "Ratnakaraṇḍodghāṭamadhyamanāmopadeśaḥ", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/891"
  },
  {
    id: "md_913",
    dsbc_id: 913,
    category: "madhyamaka",
    title_thai: "ภาวนายคัม",
    title_sanskrit: "bhāvanāyogam",
    title_english: "bhāvanāyogam",
    folder: "madhyamaka/0913_bh_van_yogam",
    priority: 45,
    status: "pending",
    description: "ภาวนายคัม — คัมภีร์มัธยมกะ (DSBC 913)",
    chapters_count: 1,
    chapters: [
      { id: 1, title_thai: "bhāvanāyogam", title_sanskrit: "bhāvanāyogam", status: "pending" },
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/913"
  },
];
