// ข้อมูลคัมภีร์สรวาสติวาท (Sarvāstivāda) — เตรียมพร้อมแปล
const SARVASTIVADA_DATA = [
    {
        id: "sa_abhi_1",
        category: "abhidharma",
        title_thai: "อภิธรรมโกศ",
        title_sanskrit: "Abhidharmakośakārikā",
        title_english: "Treasury of Abhidharma",
        author: "วสุพันธุ (Vasubandhu)",
        century: "คริสต์ศตวรรษที่ 4-5",
        dsbc_id: 96,
        priority: 1,
        status: "pending",
        description: "คัมภีร์สรุปอภิธรรมของสรวาสติวาท-ไวภาษิก อย่างเป็นระบบ 8 บาท — คัมภีร์อ้างอิงมาตรฐานของพุทธอินเดีย",
        chapters_count: 8,
        chapters: [
            { id: 1, title_thai: "ธาตุนิเทศ", title_sanskrit: "dhātu-nirdeśa", status: "pending" },
            { id: 2, title_thai: "อินทรียนิเทศ", title_sanskrit: "indriya-nirdeśa", status: "pending" },
            { id: 3, title_thai: "โลกนิเทศ", title_sanskrit: "loka-nirdeśa", status: "pending" },
            { id: 4, title_thai: "กรรมนิเทศ", title_sanskrit: "karma-nirdeśa", status: "pending" },
            { id: 5, title_thai: "อนุสัยนิเทศ", title_sanskrit: "anuśaya-nirdeśa", status: "pending" },
            { id: 6, title_thai: "มรรคบุคคลนิเทศ", title_sanskrit: "mārga-pudgala-nirdeśa", status: "pending" },
            { id: 7, title_thai: "ญาณนิเทศ", title_sanskrit: "jñāna-nirdeśa", status: "pending" },
            { id: 8, title_thai: "สมาธินิเทศ", title_sanskrit: "samādhi-nirdeśa", status: "pending" }
        ],
        source_url: "https://www.dsbcproject.org/canon-text/book/96"
    },
    {
        id: "sa_abhi_2",
        category: "abhidharma",
        title_thai: "ชฌานปรัสถาน",
        title_sanskrit: "Jñānaprasthānam śāstram",
        title_english: "Course of Knowledge",
        author: "พระกาตยายนิบุตร",
        century: "ปรับปรุงในสังคายนาสมัยกนิษกะ (ค.ศ. 158-176)",
        dsbc_id: 97,
        priority: 2,
        status: "pending",
        description: "คัมภีร์อภิธรรมหลักของสรวาสติวาท เดิมชื่อ Aṣṭagrantha (แปดคัมภีร์) รากฐานของระบบอภิธรรมทั้งหมด",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "mūla-śāstram", status: "pending" }],
        source_url: "https://www.dsbcproject.org/canon-text/book/97"
    },
    {
        id: "sa_abhi_3",
        category: "abhidharma",
        title_thai: "อภิธรรมทีป",
        title_sanskrit: "Abhidharmadīpaḥ",
        title_english: "Lamp of Abhidharma",
        dsbc_id: 94,
        priority: 3,
        status: "pending",
        description: "อรรถกถาอธิบายอภิธรรมสรวาสติวาทเพิ่มเติม",
        chapters_count: 5,
        chapters: [
            { id: 1, title_thai: "บทที่ 1", title_sanskrit: "prathamo'dhyāyaḥ", status: "pending" },
            { id: 2, title_thai: "บทที่ 2", title_sanskrit: "dvitīyo'dhyāyaḥ", status: "pending" },
            { id: 3, title_thai: "บทที่ 3", title_sanskrit: "tṛtīyo'dhyāyaḥ", status: "pending" },
            { id: 4, title_thai: "บทที่ 4", title_sanskrit: "caturtho'dhyāyaḥ", status: "pending" },
            { id: 5, title_thai: "บทที่ 5", title_sanskrit: "pañcamo'dhyāyaḥ", status: "pending" }
        ],
        source_url: "https://www.dsbcproject.org/canon-text/book/94"
    },
    {
        id: "sa_vin_1",
        category: "vinaya",
        title_thai: "มูลสรวาสติวาทวินัยวัตถุ",
        title_sanskrit: "Mūlasarvāstivāda-vinayavastu",
        title_english: "Mūlasarvāstivāda Vinaya Vastu",
        dsbc_id: 91,
        priority: 4,
        status: "pending",
        description: "คัมภีร์วินัยของมูลสรวาสติวาท 17 vastu — ยังใช้ในพุทธธิเบต ปกคลุมเอเชียตะวันออกเฉียงใต้ในอดีต",
        chapters_count: 17,
        chapters: Array.from({ length: 17 }, (_, i) => ({
            id: i + 1,
            title_thai: `วัตถุที่ ${i + 1}`,
            title_sanskrit: `vastu`,
            status: "pending"
        })),
        source_url: "https://www.dsbcproject.org/canon-text/book/91"
    },
    {
        id: "sa_vin_2",
        category: "vinaya",
        title_thai: "ปราติโมกษสูตร",
        title_sanskrit: "Prātimokṣasūtram",
        title_english: "Prātimokṣa Sūtra",
        dsbc_id: 92,
        priority: 5,
        status: "pending",
        description: "ศีลของภิกษุในนิกายสรวาสติวาท",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "prātimokṣa", status: "pending" }],
        source_url: "https://www.dsbcproject.org/canon-text/book/92"
    },
    {
        id: "sa_vin_3",
        category: "vinaya",
        title_thai: "ภิกษุณีวินัย",
        title_sanskrit: "Bhikṣuṇī vinaya",
        title_english: "Bhikṣuṇī Vinaya",
        dsbc_id: 88,
        priority: 6,
        status: "pending",
        description: "วินัยของภิกษุณีในนิกายสรวาสติวาท — ต้นฉบับสันสกฤตยังเหลือรอด",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "bhikṣuṇī-vinaya", status: "pending" }],
        source_url: "https://www.dsbcproject.org/canon-text/book/88"
    },
    {
        id: "sa_vin_4",
        category: "vinaya",
        title_thai: "วินัยสูตร",
        title_sanskrit: "Vinaya sūtram",
        title_english: "Vinaya Sūtra",
        dsbc_id: 93,
        priority: 7,
        status: "pending",
        description: "พระวินัยสูตรรวมของนิกายสรวาสติวาท",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "vinaya-sūtra", status: "pending" }],
        source_url: "https://www.dsbcproject.org/canon-text/book/93"
    },
    {
        id: "sa_vin_5",
        category: "vinaya",
        title_thai: "วินัยวินิจฉัย อุปาลิปริปฤจฉา",
        title_sanskrit: "Vinayaviniścaya upāliparipṛcchā",
        title_english: "Questions of Upāli on Vinaya",
        dsbc_id: 62,
        priority: 8,
        status: "pending",
        description: "พระอุบาลีทูลถามวินัยแก่พระพุทธเจ้า",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "upāli-paripṛcchā", status: "pending" }],
        source_url: "https://www.dsbcproject.org/canon-text/book/62"
    },
    {
        id: "sa_aga_1",
        category: "agama",
        title_thai: "มหาปราติหาริยสูตร",
        title_sanskrit: "Mahāprātihāryasūtra",
        title_english: "Great Miracle Sūtra",
        priority: 9,
        status: "pending",
        description: "พระสูตรว่าด้วยปาฏิหาริย์อันยิ่งใหญ่ของพระพุทธเจ้า — พระสูตรอิสระนอก 4 อาคม",
        chapters_count: 1,
        chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "mahāprātihārya", status: "pending" }]
    }
];
