const TANTRA_DATA = [
  // ── 1. Kriyā Tantra ──────────────────────────────
  {
    id: "tn_kriya_1",
    category: "kriya",
    title_thai: "อารยมัญชุศรีมูลกัลป",
    title_sanskrit: "Āryamañjuśrīmūlakalpam",
    title_english: "The Noble Root Manual of Mañjuśrī",
    dsbc_id: 78,
    page_id: 142,
    editor: "Shastri, M. M. T. Ganapati",
    century: "คริสต์ศตวรรษที่ 8-9",
    priority: 1,
    status: "completed",
    description: "คัมภีร์กัณฑ์ที่ใหญ่ที่สุดของมัญชุศรี — รวบรวมมนตรา มณฑล และพิธีกรรมของพระโพธิสัตว์มัญชุศรี",
    chapters_count: 55,
    chapters: Array.from({ length: 55 }, (_, i) => ({
      id: i + 1,
      title_thai: `ปัฏลที่ ${i + 1}`,
      title_sanskrit: `atha ${['prathama', 'dvitīya', 'tṛtīya', 'caturtha', 'pañcama', 'ṣaṣṭha', 'saptama', 'aṣṭama', 'navama', 'daśama', 'ekādaśa', 'dvādaśa', 'trayodaśa', 'caturdaśa', 'pañcadaśa', 'ṣoḍaśa', 'saptadaśa', 'aṣṭādaśa', 'ekonaviṁśa', 'viṁśa', 'ekaviṁśa', 'dvāviṁśa', 'trayoviṁśatitama', 'caturviṁśatitama', 'pañcaviṁśatitama', 'ṣaḍviṁśatitama', 'saptaviṁśatitama', 'aṣṭāviṁśatitama', 'ekonatriṁśa', 'triṁśa', 'ekatriṁśa', 'dvātriṁśa', 'trayastriṁśa', 'catustriṁśa', 'pañcatriṁśa', 'ṣaṭtriṁśa', 'saptatriṁśa', 'aṣṭātriṁśa', 'ekonacatvāriṁśa', 'catvāriṁśa', 'ekacatvāriṁśa', 'dvicatvāriṁśa', 'tricatvāriṁśa', 'catuścatvāriṁśa', 'pañcacatvāriṁśa', 'ṣaṭcatvāriṁśa', 'saptacatvāriṁśa', 'aṣṭacatvāriṁśa', 'ekonapañcāśa', 'pañcāśa', 'ekapañcāśa', 'dvipañcāśa', 'tripañcāśa', 'catuḥpañcāśa', 'pañcapañcāśa'][i]}ḥ paṭalavisaraḥ`,
      status: "completed"
    })),
    source_url: "https://www.dsbcproject.org/canon-text/book/78"
  },
  {
    id: "tn_kriya_2",
    category: "kriya",
    title_thai: "อโมฆปาสกัปราชา ภาค 6",
    title_sanskrit: "Amoghapāśakalparāja Part VI",
    title_english: "The King of Rituals of Amoghapāśa Part VI",
    dsbc_id: 792,
    editor: "SasakiItoTakumi",
    century: "คริสต์ศตวรรษที่ 11",
    priority: 2,
    status: "pending",
    description: "คัมภีร์พิธีกรรมของพระโพธิสัตว์อโมฆปาส (อวโลกิเตศวร) — ภาคที่ 6",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "amoghapāśakalparāja", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/792"
  },
  {
    id: "tn_kriya_3",
    category: "kriya",
    title_thai: "อโมฆปาสกัปราชา ภาค 7",
    title_sanskrit: "Amoghapāśakalparāja Part VII",
    title_english: "The King of Rituals of Amoghapāśa Part VII",
    dsbc_id: 794,
    priority: 3,
    status: "pending",
    description: "คัมภีร์พิธีกรรมของพระโพธิสัตว์อโมฆปาส — ภาคที่ 7",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "amoghapāśakalparāja", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/794"
  },

  // ── 2. Yoga Tantra ────────────────────────────────
  {
    id: "tn_yoga_1",
    category: "yoga",
    page_id: 143,
    title_thai: "สรวะตถาคตทัตวาสังคหะ",
    title_sanskrit: "Sarva tathāgata tattva saṅgrahaḥ",
    title_english: "The Compendium of the Reality of All Tathāgatas",
    dsbc_id: 84,
    editor: "Chandra, Lokesh",
    century: "คริสต์ศตวรรษที่ 7-8",
    priority: 4,
    status: "completed",
    description: "ตันตระหลักของโยคตันตระ — อธิบายมณฑลของพระธยานิพุทธ 5 พระองค์ และพิธีกรรมการประทับจิต",
    chapters_count: 26,
    chapters: Array.from({ length: 26 }, (_, i) => ({
      id: i + 1,
      title_thai: `${['ปฐมาธิยาย', 'ทุติยาธยาย', 'ตติยาธยาย', 'จตุรฺถาธยาย', 'ปัญจมธยาย', 'ษัษฐมธยาย', 'สัปตมธยาย', 'อัษฏมธยาย', 'นวมธยาย', 'ทศมธยาย', 'เอกาทศมธยาย', 'ทวาทศมธยาย', 'ตรโยทศมธยาย', 'จตุรฺทศมธยาย', 'ปัญจทศมธยาย', 'โษฑศมธยาย', 'สัปตทศมธยาย', 'อัษฎาทศมธยาย', 'เอกานนวินศติมธยาย', 'วินศติตมธยาย', 'เอกวินศติตมธยาย', 'ทวาวินศติตมธยาย', 'ตรโยวินศติตมธยาย', 'จตุรวินศติตมธยาย', 'ปัญจวินศติตมธยาย', 'ษัฑวินศติตมธยาย'][i]}`,
      title_sanskrit: `${['Prathamaḥ', 'Dvitīyaḥ', 'Tṛtīyaḥ', 'Caturthaḥ', 'Pañcamaḥ', 'Ṣaṣṭhamaḥ', 'Saptamaḥ', 'Aṣṭamaḥ', 'Navamaḥ', 'Daśamaḥ', 'Ekādaśamaḥ', 'Dvādaśamaḥ', 'Trayodaśamaḥ', 'Caturdaśamaḥ', 'Pañcadaśamaḥ', 'Ṣoḍaśamaḥ', 'Saptadaśamaḥ', 'Aṣṭādaśamaḥ', 'Ekānnaviṁśatimaḥ', 'Viṁśatitamaḥ', 'Ekaviṁśatitamaḥ', 'Dvāviṁśatitamaḥ', 'Trayoviṁśatitamaḥ', 'Caturviṁśatitamaḥ', 'Pañcaviṁśatimaḥ', 'Ṣaḍviṁśatimaḥ'][i]}`,
      status: "completed"
    })),
    source_url: "https://www.dsbcproject.org/canon-text/book/84"
  },
  {
    id: "tn_yoga_2",
    category: "yoga",
    title_thai: "สรวทุรคติปริโศธนตันตระ",
    title_sanskrit: "Sarvadurgatipariśodhana tantra",
    title_english: "The Tantra for Eliminating All Evil Destinies",
    dsbc_id: 730,
    century: "คริสต์ศตวรรษที่ 7-8",
    priority: 5,
    status: "pending",
    description: "ตันตระว่าด้วยการชำระล้างทุรคติทั้งปวง — พิธีกรรมเพื่อหลุดพ้นจากอบายภูมิ",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "sarvadurgatipariśodhana tantra", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/730"
  },

  // ── 3. Yoginī Tantra ──────────────────────────────
  {
    id: "tn_yogini_1",
    category: "yogini",
    title_thai: "จักรสังวรตันตระ เล่ม 1",
    title_sanskrit: "Cakrasaṃvaratantram [Vol.1]",
    title_english: "The Wheel of Union Tantra Vol.1",
    dsbc_id: 80,
    editor: "Pandey, Janardan Shastri",
    century: "คริสต์ศตวรรษที่ 10-11",
    priority: 6,
    status: "pending",
    description: "โยคินีตันตระสำคัญ — อธิบายการทำสมาธิและการปฏิบัติของจักรสังวร (heruka) กับภาชิกาโยคินี",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "śrīherukābhidhānaṃ cakrasaṃvaratantram", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/80"
  },
  {
    id: "tn_yogini_2",
    category: "yogini",
    title_thai: "จักรสังวรตันตระ เล่ม 2",
    title_sanskrit: "Cakrasaṃvaratantram [Vol.2]",
    title_english: "The Wheel of Union Tantra Vol.2",
    dsbc_id: 81,
    century: "คริสต์ศตวรรษที่ 10-11",
    priority: 7,
    status: "pending",
    description: "จักรสังวรตันตระภาค 2 — พร้อมคำอธิบายของ Bhavabhaṭṭa",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "cakrasaṃvaratantram", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/81"
  },
  {
    id: "tn_yogini_3",
    category: "yogini",
    title_thai: "พุทธกปาลตันตระ",
    title_sanskrit: "Buddhakapālatantra",
    title_english: "The Buddha Skull Tantra",
    dsbc_id: 797,
    century: "คริสต์ศตวรรษที่ 10-11",
    priority: 8,
    status: "pending",
    description: "โยคินีตันตระที่กล่าวถึงพุทธกปาล (Buddhakapāla) — เทพแห่งความตายและการเกิดใหม่",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "buddhakapālatantra", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/797"
  },
  {
    id: "tn_yogini_4",
    category: "yogini",
    title_thai: "ฑาการรณวะ",
    title_sanskrit: "Ḍākārṇavaḥ",
    title_english: "The Ocean of Ḍākinīs",
    dsbc_id: 809,
    century: "คริสต์ศตวรรษที่ 10-11",
    priority: 9,
    status: "pending",
    description: "โยคินีตันตระที่สำคัญ — ว่าด้วยแม่น้ำแห่งฑากิณีและพิธีกรรมของพระนาง",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "ḍākārṇavaḥ", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/809"
  },

  // ── 4. Anuttarayoga Tantra ─────────────────────────
  {
    id: "tn_anuttara_1",
    category: "anuttara",
    title_thai: "ศรีคุหยสมาชตันตระ",
    title_sanskrit: "Śrīguhyasamājatantram",
    title_english: "The Glorious Esoteric Assembly Tantra",
    dsbc_id: 723,
    editor: "Benoytosh Bhattacharyya",
    century: "คริสต์ศตวรรษที่ 8-9",
    priority: 10,
    status: "pending",
    description: "ตันตระหลักของอนุตตรโยคะ — คัมภีร์ลับว่าด้วยการรวมเป็นหนึ่งกับพระอักโษภยพุทธะ",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "śrīguhyasamājatantram", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/723"
  },

  // ── 5. Tantra Darśana ──────────────────────────────
  {
    id: "tn_darsana_1",
    category: "darsana",
    title_thai: "อทวยวัชรสังคระ",
    title_sanskrit: "Advayavajrasaṇgrahaḥ",
    title_english: "The Collection of Advayavajra",
    dsbc_id: 82,
    editor: "Pt. Hara Prasad Shastri",
    century: "คริสต์ศตวรรษที่ 10-11",
    priority: 11,
    status: "pending",
    description: "รวมคัมภีร์ของ Advayavajra (Maitrīpa) — 21 บทว่าด้วยตันตระทรรศนะ การทำสมาธิ และมุทรา",
    chapters_count: 21,
    chapters: [
      { id: 1, title_thai: "กุทฤษฏินิรฆาตนะ", title_sanskrit: "kudṛṣṭinirghātanam", status: "pending" },
      { id: 2, title_thai: "มูลาปัตยสถูลาปัตยะ", title_sanskrit: "mūlāpattayaḥ sthūlāpattayaḥ", status: "pending" },
      { id: 3, title_thai: "ทัตวะรัตนาวลี", title_sanskrit: "tattvaratnāvalī", status: "pending" },
      { id: 4, title_thai: "ปัญจตถาคตมุทราวิวรณะ", title_sanskrit: "pañcatathāgatamudrāvivaraṇam", status: "pending" },
      { id: 5, title_thai: "เสกนิรณยะ", title_sanskrit: "sekanirṇayaḥ", status: "pending" },
      { id: 6, title_thai: "จตุรมุทรา", title_sanskrit: "caturmudrā", status: "pending" },
      { id: 7, title_thai: "เสกตันวยสังครหะ", title_sanskrit: "sekatānvayasaṁgrahaḥ", status: "pending" },
      { id: 8, title_thai: "ปัญจาการะ", title_sanskrit: "pañcākāraḥ", status: "pending" },
      { id: 9, title_thai: "มายานิรุกติ", title_sanskrit: "māyāniruktiḥ", status: "pending" },
      { id: 10, title_thai: "สวปนนิรุกติ", title_sanskrit: "svapnaniruktiḥ", status: "pending" },
      { id: 11, title_thai: "ทัตวะประกาศ", title_sanskrit: "tattvaprakāśaḥ", status: "pending" },
      { id: 12, title_thai: "อประติษฐานประกาศ", title_sanskrit: "apratiṣṭhānaprakāśaḥ", status: "pending" },
      { id: 13, title_thai: "โยคนัทธประกาศ", title_sanskrit: "yuganaddhaprakāśaḥ", status: "pending" },
      { id: 14, title_thai: "มหาสุขประกาศ", title_sanskrit: "mahāsukhaprakāśaḥ", status: "pending" },
      { id: 15, title_thai: "ทัตวะวิงศิกา", title_sanskrit: "tattvaviṁśikā", status: "pending" },
      { id: 16, title_thai: "มหายานวิงศิกา", title_sanskrit: "mahāyānaviṁśikā", status: "pending" },
      { id: 17, title_thai: "นิรเวธปัญจก", title_sanskrit: "nirbedhapañcaka", status: "pending" },
      { id: 18, title_thai: "มัธยกษัตกะ", title_sanskrit: "madhyakaṣaṭka", status: "pending" },
      { id: 19, title_thai: "เปรมปัญจก", title_sanskrit: "premapañcaka", status: "pending" },
      { id: 20, title_thai: "ทัตวะทศก", title_sanskrit: "tattvadaśaka", status: "pending" },
      { id: 21, title_thai: "อมนสิการาธาระ", title_sanskrit: "amanasikārādhāraḥ", status: "pending" }
    ],
    source_url: "https://www.dsbcproject.org/canon-text/book/82"
  },
  {
    id: "tn_darsana_2",
    category: "darsana",
    title_thai: "นิษปันนโยคาวลี",
    title_sanskrit: "Niṣpannayogāvalī",
    title_english: "The Garland of Accomplished Yoga",
    dsbc_id: 83,
    editor: "Benoytosh Bhattacharya",
    century: "คริสต์ศตวรรษที่ 11",
    priority: 12,
    status: "pending",
    description: "คัมภีร์ตันตระทรรศนะว่าด้วยโยคะที่สมบูรณ์ — ของอาจารย์อภินาคคุปตะ",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "niṣpannayogāvalī", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/83"
  },

  // ── 6. Sahajayāna ──────────────────────────────────
  {
    id: "tn_sahaja_1",
    category: "sahaja",
    title_thai: "นานาสิทโธปเทศ",
    title_sanskrit: "Nānāsiddhopadeśaḥ",
    title_english: "Instructions of Various Siddhas",
    dsbc_id: 79,
    priority: 13,
    status: "pending",
    description: "คำสอนของสิทธาจารย์หลายท่านในแนวสหชายาน — หนทางแห่งการบรรลุโดยธรรมชาติ",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "nānāsiddhopadeśaḥ", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/79"
  },

  // ── 7. Yogottara Tantra ────────────────────────────
  {
    id: "tn_yogottara_1",
    category: "yogottara",
    title_thai: "อทวยสิทธิ",
    title_sanskrit: "Advayasiddhiḥ",
    title_english: "The Attainment of Non-Duality",
    dsbc_id: 85,
    editor: "Dr. Ram Prasad Mishra",
    century: "คริสต์ศตวรรษที่ 11",
    priority: 14,
    status: "pending",
    description: "คัมภีร์โยคตันตระชั้นสูง — ว่าด้วยการบรรลุอทวยธรรม (ความเป็นหนึ่งเดียว)",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "advayasiddhiḥ", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/85"
  },
  {
    id: "tn_yogottara_2",
    category: "yogottara",
    title_thai: "ศรีวัชรไภรวะมหาโยคตันตระ",
    title_sanskrit: "Śrīvajrabhairava mahāyogatantram",
    title_english: "The Glorious Vajrabhairava Great Yoga Tantra",
    dsbc_id: 86,
    priority: 15,
    status: "pending",
    description: "ตันตระของพระวัชรไภรวะ — อวตารที่ดุร้ายของมัญชุศรีผู้พิชิตความตาย",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "śrīvajrabhairava mahāyogatantram", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/86"
  },
  {
    id: "tn_yogottara_3",
    category: "yogottara",
    title_thai: "จัณฑมหาโรษณะตันตระ",
    title_sanskrit: "Caṇḍamahāroṣaṇa tantra",
    title_english: "The Fierce Great Wrath Tantra",
    dsbc_id: 762,
    priority: 16,
    status: "pending",
    description: "โยคุตตรตันตระว่าด้วยพระจัณฑมหาโรษณะ — พุทธผู้ทรงพิโรธ",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "caṇḍamahāroṣaṇa tantra", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/762"
  },
  {
    id: "tn_yogottara_4",
    category: "yogottara",
    title_thai: "ศรีสรวพุทธสมาโยคฑากินีชาลสังวรนามตันตระ",
    title_sanskrit: "Śrīsarvabuddhasamāyogaḍākinījālasamvaranāmatantram",
    title_english: "The Union of All Buddhas and the Net of Ḍākinīs",
    dsbc_id: 933,
    priority: 17,
    status: "pending",
    description: "ตันตระระดับสูงที่กล่าวถึงการรวมพุทธทั้งปวงและตาข่ายแห่งฑากิณี",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "śrīsarvabuddhasamāyogaḍākinījālasamvara", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/933"
  },

  // ── 8. Kriyātantraṭīkā ─────────────────────────────
  {
    id: "tn_kriya_tika_1",
    category: "kriya_tika",
    title_thai: "กัลปโกตามารีจีสาธนะ",
    title_sanskrit: "Kalpoktamārīcīsādhanam",
    title_english: "The Practice of Mārīcī according to the Kalpa",
    dsbc_id: 728,
    priority: 18,
    status: "pending",
    description: "คัมภีร์สาธนะของพระมารีจี (พระโพธิสัตว์แห่งรัศมี) — ตามที่กล่าวในกัป",
    chapters_count: 1,
    chapters: [{ id: 1, title_thai: "ตัวคัมภีร์", title_sanskrit: "kalpoktamārīcīsādhanam", status: "pending" }],
    source_url: "https://www.dsbcproject.org/canon-text/book/728"
  }
];
